spring.application.name=autoscout
# 1. Database Connection (Where is it?)
spring.datasource.url=jdbc:mysql://localhost:3306/autoscout_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# 2. Hibernate Magic (Auto-create tables)
# This tells Java: "If the table doesn't exist, create it for me!"
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true